modLoader="javafml"
loaderVersion="[0,)"
license="MIT"

[[mods]]
modId="flatedit"
version="${version}"
displayName="FlatEdit+"
authors="Boxadactle"
description='''A rework of the horrific superflat creation screen.'''
logoFile='icon.png'

[[dependencies.flatedit]]
modId="forge"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.flatedit]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.flatedit]]
modId="boxlib"
mandatory=true
versionRange="[16.0.0,17.0.0)"
ordering="NONE"
side="CLIENT"