# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=8.0.1
group=dev.boxadactleflatedit
java_version=25

# Common
mod_name=FlatEdit+
mod_author=Boxadactle
mod_id=flatedit
license=GPLv3
credits=
description=A rework of the horrific superflat creation screen.
enabled_platforms=neoforge,fabric
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-2

minecraft_version=26.2
minecraft_version_range=[26,27)
minecraft_version_range_fabric=26.x

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.156.0+26.2
fabric_loader_version=0.19.3
modmenu_version=20.0.1

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.2.0.32-beta
neoforge_loader_version_range=[4,)

# BoxLib
boxlib_version=22.0.1
boxlib_version_range = [21, 23)
boxlib_version_range_fabric=22.x

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

#publishing
game_versions = 26.2
project_id_curseforge = 1261053
project_id_modrinth = sS0r4bFm
release_type = release
changelog_file = CHANGELOG.md
