modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="flatedit"
version="${version}"
displayName="FlatEdit+"
logoFile="icon.png"
description='''
A rework of the horrific superflat creation screen.
'''

[[dependencies.flatedit]]
   modId="neoforge"
   mandatory=true
   versionRange="[20,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.flatedit]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.21,1.22)"
   ordering="NONE"
   side="BOTH"

[[dependencies.flatedit]]
   modId = "boxlib"
   type = "required"
   versionRange = "[15.0.0, 16.0.0)"
   ordering = "NONE"
   side = "BOTH"

[[mixins]]
   config = "flatedit.mixins.json"